version: '3'

services:

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 3001:27017
    volumes:
      - mongodb:/data/db

  node-app:
    build: .
    ports:
      - 3000:3000
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/clear-extension
      - PORT=3000
    depends_on:
      - mongodb

volumes:
  mongodb: {}